const errorTypes = {
    USER_NOT_FOUND_ERROR: "USER_NOT_FOUND_ERROR",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    USER_DUPLICATION_ERROR: "USER_DUPLICATION_ERROR",
    AUTHENTICATION_FAILED_ERROR: "AUTHENTICATION_FAILED_ERROR",
    UNAUTHORIZED_ERROR: "UNAUTHORIZED_ERROR"
}

export default errorTypes;